sudo: false
language: node_js
node_js:
  - "0.10"  # end of life
  - "0.12"  # maintenance
  - "4"     # lts
  - "6"     # lts
  - "7"     # stable
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.10"
    - node_js: "0.12"
cache:
  directories:
    - $HOME/.npm  # npm's cache
    - $HOME/.yarn-cache  # yarn's cache
install:
  - ./.travis/node-install.bash
before_script:
  - ./.travis/node-verify.bash
