language: node_js
node_js:
  - "4"
  - "5"
  - "6"
env:
  - CXX=g++-4.8
before_script: "./node_modules/.bin/cake compile"
script: "PORT=9778 npm test"
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
